//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamEnroll
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int Eid { get; set; }
        public string UserName { get; set; }
        public string CourseName { get; set; }
        public int Tid { get; set; }
        public System.DateTime Time { get; set; }
        public int Value { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual ExamTime ExamTime { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual User User { get; set; }
        public virtual Value Value1 { get; set; }
    }
}
